title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Start a discussion about anything related to Skuber+ Client.

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What would you like to discuss?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Any additional context or details.
