blank_issues_enabled: false
contact_links:
  - name: Question & Discussion
    url: https://github.com/Wondermove-Inc/Skuberplus-Client-Community/discussions
    about: For questions or general discussion, please use Discussions instead of Issues.
