// 🎯 컬럼 우선순위 및 레이아웃 설정 통합 정의
export const COLUMN_PRIORITY = {
  NAME: 120,
  STATUS_ICON: 99,
  NAMESPACE: 90,
  CONTAINERS: 80,
  CPU_USAGE: 70,
  MEMORY_USAGE: 60,
  RESTARTS: 50,
  OWNERS: 40,
  IP: 35,
  NODE: 30,
  QOS: 20,
  AGE: 10,
  STATUS: 0,
};

// 🔧 컬럼별 레이아웃 설정 (CSS 클래스명과 매칭)
export const COLUMN_LAYOUT = {
  name: {
    resizable: true,
    defaultWidth: 200,
    minWidth: 150,
    maxWidth: 400,
    flex: "2 1",
    className: "name",
  },
  namespace: {
    resizable: true,
    defaultWidth: 120,
    minWidth: 80,
    maxWidth: 200,
    flex: "1 1",
    className: "namespace",
  },
  age: {
    resizable: true,
    defaultWidth: 80,
    minWidth: 60,
    maxWidth: 120,
    flex: "0 1",
    className: "age",
  },
  containers: {
    resizable: true,
    defaultWidth: 80,
    minWidth: 60,
    maxWidth: 120,
    flex: "0 1",
    className: "containers",
  },
  "cpu-usage": {
    resizable: true,
    defaultWidth: 90,
    minWidth: 70,
    maxWidth: 150,
    flex: "0 1",
    className: "cpu-usage",
  },
  "memory-usage": {
    resizable: true,
    defaultWidth: 90,
    minWidth: 70,
    maxWidth: 150,
    flex: "0 1",
    className: "memory-usage",
  },
  restarts: {
    resizable: true,
    defaultWidth: 70,
    minWidth: 50,
    maxWidth: 100,
    flex: "0 1",
    className: "restarts",
  },
  node: {
    resizable: true,
    defaultWidth: 120,
    minWidth: 80,
    maxWidth: 250,
    flex: "1 1",
    className: "node",
  },
  ip: {
    resizable: true,
    defaultWidth: 120,
    minWidth: 90,
    maxWidth: 180,
    flex: "0 1",
    className: "ip",
  },
  // 🚫 리사이즈 불가능한 고정 컬럼들
  warning: {
    resizable: false,
    defaultWidth: 40,
    minWidth: 40,
    maxWidth: 40,
    flex: "0 0",
    className: "warning",
  },
  ready: {
    resizable: false,
    defaultWidth: 80,
    minWidth: 80,
    maxWidth: 80,
    flex: "0 0",
    className: "ready",
  },
  status: {
    resizable: false,
    defaultWidth: 100,
    minWidth: 100,
    maxWidth: 100,
    flex: "0 0",
    className: "status",
  },
};
